name: extism_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  ffi: ^2.1.2
  path: ^1.9.0
  uuid: ^4.4.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.24.0

ffigen:
  output: 'lib/extism/generated_bindings.dart'
  llvm-path: 
    - 'D:/Program Files/LLVM/'
  headers:
    entry-points:
      - 'assets/lib/windows/extism.h'
  name: 'LibExtism'